name: todo_list
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  basic_utils: ^4.2.0
  easy_localization: ^3.0.1
  freezed_annotation: ^2.1.0
  auto_route: ^5.0.1
  get_it: ^7.2.0
  dio: ^4.0.6
  equatable: ^2.0.5
  logger: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.5
  easy_debounce: ^2.0.2+1
  uuid: ^3.0.6
  flutter_form_builder: ^7.6.0
  flutter_staggered_animations: ^1.1.1
  datetime_picker_formfield_new: ^2.0.0
  global_configs: ^1.1.2
  json_annotation: ^4.7.0
  encrypted_shared_preferences: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.1
  freezed: ^2.1.0+1
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/cfg/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
